### ISSUE TITLE
Not reading the data file because of Environment setting

### ISSUE THREAD

**Issue by alexeylark** [trentsartain/Neural-Network#1]
In the Program.cs there is a SetupFromFile() method, which does the splitting of a fileContent. When it splits the fileContent with Environment.NewLine first parameter, the new line splitter is \r\n in my environment and so the function doesn't split the fileContent. It causes expected error with unability to Load all data from file.

**Comment by trentsartain** [comment]
Sorry for the delay on this.  

I wrote that thinking that the user would just edit and save the file using their environment.  Typically, using Environment.NewLine as the splitter is safest as if the user were to edit and save the file in their environment and I didn't use Environment.NewLine, they would have to edit the code rather than the data file itself.  I think using Environment.NewLine is safest.  Do you have another suggestion?
